apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: familog-backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: familog-backend
    spec:
      containers:
      - image: gcr.io/familog-193013/familog:14b772a
        imagePullPolicy: Always
        name: familog-backend
