apiVersion: v1
kind: Service
metadata:
  name: familog-backend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: grpc
  selector:
    app: familog-backend
