apiVersion: v1
kind: Service
metadata:
  name: grpcwebproxy
spec:
  selector:
    app: grpcwebproxy
  ports:
  - protocol: TCP
    port: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: familog-backend
spec:
  selector:
    app: familog-backend 
  ports:
  - protocol: TCP
    port: 8000
